### ISSUE TITLE
Build 0 of 7.19.0 gets picked up.  

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/ipython-feedstock#125]
If I start with a fairly fresh env and install ipython:

`conda install ipython`

I get:

`ipython                   7.19.0           py38h9bb44b7_0    conda-forge`

which is almost right -- 7.19.0 is the latest. However, there is a newer build:

`osx-64/ipython-7.19.0-py38h9bb44b7_1.tar.bz2`

on the conda-forge channel on Anaconda.org

I *think* the only difference is that the new build depends on an older jedi -- but that's key, because auto-complete does NOT work with the latest jedi (which is, of course, whey the new build was built)

Why am I not getting the latest build??

On the conda-forge list, it was suggested that the new jedi was taking precedence over the newer iPython build. Which sticks me as a bug in conda -- but it's pretty bad for iPython, which is going to be broken for most folks installing it :-(

I can force an older jedi, and all is well, but that's not a solution many people will figure out on their own.

Other than a change to conda, maybe the older build could be removed from the conda-forge channel?

**Comment by bollwyvl** [comment]
Oh no, I feel your pain!

Yeah, I don't know why it's pulling it. About the only lever we have is to get it marked `broken`... that won't break people's locked environments. but you are right, I think (our/my) intent was that `0` shouldn't get picked up...

**Comment by bollwyvl** [comment]
Those builds should be marked broken: please re-open this issue if you continue to see problems!
