### ISSUE TITLE
IPython 7.30.0 yanked from PyPI; conda-forge version remains

### ISSUE THREAD

**Issue by klauer** [conda-forge/ipython-feedstock#152]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: As noted in #151, IPython 7.30.0 has been yanked from PyPI as it breaks some asyncio functionality. 7.30.1 is a hotfix release that addresses it.

Would it be possible for the maintainers to remove (or request removal of) 7.30.0? Downstream project constraints could potentially get a bit messy if it remains.

(And thanks for maintaining the feedstock!)

Ref: https://pypi.org/project/ipython/7.30.0/#history

**Comment by Carreau** [comment]
I believe this should be done with a PR against https://github.com/conda-forge/admin-requests ? I've never done it.

**Comment by Carreau** [comment]
opened conda-forge/admin-requests#355

**Comment by klauer** [comment]
Thank you, @Carreau!

**Comment by bollwyvl** [comment]
🧙
