### ISSUE TITLE
pip check fails due to: ipython 8.0.1 requires black, which is not installed.

### ISSUE THREAD

**Issue by beenje** [conda-forge/ipython-feedstock#164]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I have several conda recipes that depend on `ipython` and use `pip check` in the tests.
conda-build started to fail with:

```
+ pip check
Tests failed for...
ipython 8.0.1 requires black, which is not installed.
```

I guess it's linked to https://github.com/conda-forge/ipython-feedstock/pull/163

Should this be reverted? Or should I stop using `pip check` (it's added by `grayskull`)?

**Comment by Carreau** [comment]
next version of IPython will remove the dependency on IPython.

**Comment by bollwyvl** [comment]
My mistake, I recall that those changes had landed upstream (maybe even by
me), but somehow thought we had missed updating them here... I'll revert
that change.

**Comment by bollwyvl** [comment]
I started #165, and should be up in a couple hours. If you need something faster, you can add a temporary pin to your recipe, e.g. `ipython !=8.0.1=*_1` or something.

If the problem persists for you (there's no telling with the conda solver sometime) we can look into getting the offending builds pulled from the repo metadata.

**Comment by bollwyvl** [comment]
the builds are up on anaconda.org, but not yet on CDN... once they are (see the [status page](https://conda-forge.org/status/) for a rough idea), we'll have a better idea of what `conda` and `mamba` make of the options and whether we need more drastic measures.

```
linux-64/ipython-8.0.1-py310hff52083_2.tar.bz2
linux-64/ipython-8.0.1-py38h578d9bd_2.tar.bz2
linux-64/ipython-8.0.1-py39hf3d152e_2.tar.bz2 
linux-aarch64/ipython-8.0.1-py310h4c7bcd0_2.tar.bz2
linux-aarch64/ipython-8.0.1-py38he3eb160_2.tar.bz2
linux-aarch64/ipython-8.0.1-py39h4420490_2.tar.bz2
linux-ppc64le/ipython-8.0.1-py310h194a6c8_2.tar.bz2
linux-ppc64le/ipython-8.0.1-py38h8328f6c_2.tar.bz2
linux-ppc64le/ipython-8.0.1-py39h0b1cf3c_2.tar.bz2
osx-64/ipython-8.0.1-py310h2ec42d9_2.tar.bz2
osx-64/ipython-8.0.1-py38h50d1736_2.tar.bz2
osx-64/ipython-8.0.1-py39h6e9494a_2.tar.bz2
osx-arm64/ipython-8.0.1-py310hbe9552e_2.tar.bz2
osx-arm64/ipython-8.0.1-py38h10201cd_2.tar.bz2
osx-arm64/ipython-8.0.1-py39h2804cbe_2.tar.bz2
win-64/ipython-8.0.1-py310h5588dad_2.tar.bz2
win-64/ipython-8.0.1-py38haa244fe_2.tar.bz2
win-64/ipython-8.0.1-py39hcbf5309_2.tar.bz2
```
