### ISSUE TITLE
Switch to no-arch.

### ISSUE THREAD

**Issue by Carreau** [conda-forge/ipython-feedstock#32]
I'm about to release IPython 5.5. and 6.2 this afternoon likely. 
I t would be nice to switch both to `python: noarch` to decrease the load on CI services.

**Comment by Carreau** [comment]
See https://github.com/conda-forge/conda-smithy/issues/485

**Comment by bollwyvl** [comment]
Suggest closing this, as there are way too many platform-specific runtime dependencies to consider `noarch: python` at this time. `na: p` is basically incompatible with platform selectors.

One could imagine shifting these dependencies to a separate metapackage, e.g. `ipython-platform-deps`, and then being able to ship `ipython` as `na: p` relying on _that_ package. That's really just passing the buck, but would make new `ipython` releases much faster. Not sure anybody has done that, yet.
