### ISSUE TITLE
Change python-simplegeneric requirement to simplegeneric

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/ipython-feedstock#9]
conda cannot install both `simplegeneric` and `python-simplegeneric` in the same environment, see conda-forge/conda-forge.github.io#180. Attempting to upgrade ipython from a version in the `defaults` channel can results in a situation where conda unusable.  

The easy solution to this would be to change the run requirement of `ipython` from `python-simplegeneric` to `simplegeneric` although I expect this may be controversial due to the unresolved package naming recommendation.

**Comment by jjhelmus** [comment]
Package naming policy conda-forge/conda-forge.github.io#18

**Comment by jakirkham** [comment]
Fixed by PR ( https://github.com/conda-forge/ipython-feedstock/pull/10 ).

**Comment by jakirkham** [comment]
Oops, thought I had pushed closed. Thanks @minrk.
