### ISSUE TITLE
5.x branch needs update to python 3.7

### ISSUE THREAD

**Issue by mkoeppe** [conda-forge/ipython-feedstock#93]
To support sagelib, we need an ipython 5.x in conda-forge with python 3.7

see https://github.com/conda-forge/sagelib-feedstock/issues/87#issuecomment-578412901

**Comment by isuruf** [comment]
@mkoeppe, all you've got to do is,

1. checkout the 5.x branch
2. Install `conda-smithy`
3. Run `conda smithy rerender -c auto` in the root of the git repo.
4. Push the changes and make a PR

**Comment by mkoeppe** [comment]
Thank you! This is now #94
